### ISSUE TITLE
Augment type definitions in gem RBIs with annotations

### ISSUE THREAD

**Issue by egiurleo** [Shopify/tapioca#1048] opened 2022-07-08 20:18 UTC
Currently, if a type definition exists in gem RBIs and annotations, a project will always use the gem RBIs and ignore the annotation. Annotations should be able to override gem RBIs if they have more type information (e.g. annotations have a sig and gem RBIs don't).

**Comment by Morriar** [comment] 2022-07-12 16:07
They already do and you can see this with a simple example:

```rb
# file: sorbet/rbi/annotations/foo.rbi
# typed: true

class Bar
  def bar; end
end

class Foo
  sig { params(blk: T.proc.bind(Bar).void).void }
  def foo(&blk); end
end
```

```rb
# file: sorbet/rbi/gems/foo@0.0.1.rbi
# typed: true

class Bar
  def bar; end
end

class Foo
  def foo(&blk); end
end
```

```rb
# file: main.rb
# typed: strict

Foo.new.foo do
  T.reveal_type(self) # => Bar
end
```

In you case the problem is that the RBI annotations was pulled with the option `typed_override: ignore`. So the definition is not seen by Sorbet.

I'm closing this issue and moving the problem to https://github.com/Shopify/tapioca/issues/1053.

**Closed by Morriar** 2022-07-12 16:07 UTC
Labels: bug
