### ISSUE TITLE
tapioca dsl command for ActiveRecord model files seem to always have nilable column values for certain types

### ISSUE THREAD

**Issue by seansu4you87** [Shopify/tapioca#1642] opened 2023-09-05 06:36 UTC
I'm using `tapioca dsl` to generate .rbi files for my ActiveRecord models.  I'm migrating from `sorbet-rails`.

I noticed that the generated column values all seem to be nilable, even for columns that have been migrated as `null: false`.  Here is an example:
```
    sig { returns(T.nilable(::ActiveSupport::TimeWithZone)) }
    def created_at; end
```

The timestamp columns `created_at` and `updated_at` for all of my models all are nilable, even though the schema has their type as `null: false`.

Is there a way to force these common column values to my preferred type without having to type everything out myself?

If there is more documentation on how the ActiveRecord DSL generation works, that would be amazing - I've noticed other issues with other columns (nilability of association methods, etc) that I would like to configure better

**Comment by Morriar** [comment] 2023-09-05 14:31
Duplicate of https://github.com/Shopify/tapioca/issues/600#issuecomment-1022702996.

The issue is that any value of an ActiveRecord object are indeed nilable before it's saved.

Take this as an example:

```rb
MyModel.new.created_at
=> nil
```

**Closed by Morriar** 2023-09-05 14:31 UTC
