### ISSUE TITLE
Investigate the possibility of generating DSLs for test classes

### ISSUE THREAD

**Issue by vinistock** [Shopify/tapioca#715] opened 2022-01-24 20:36 UTC
Currently, we do not require test files as a part of the DSL generation process. However, there are certain test classes that do have DSLs generated with meta-programming. One example is tests that inherit from `ActionView::TestCase`, which get the helpers they test automatically included by Rails.

Investigate the possibility of running the DSL generators for test classes and whether that causes any sort of conflicts. Based on some preliminary explorations, we will have to
- Stop test from auto-running as they are required (or else we will run the entire test suite)
- Require the gems under the test group
- Modify the `$LOAD_PATH` so that we can require files under `test`
- And then require tests

**Comment by Morriar** [comment] 2023-01-18 16:32
Duplicate of https://github.com/Shopify/tapioca/issues/570.

**Closed as not planned by Morriar** 2023-01-18 16:32 UTC
Labels: enhancement
