### ISSUE TITLE
Tapioca rendering incomplete RBI for httpclient gem

### ISSUE THREAD

**Issue by RyanBrushett** [Shopify/tapioca#201] opened 2021-01-11 18:17 UTC
When running tapioca sync or generate on a project that includes the httpclient gem, the resulting RBI file has a syntax error:

```
...

WebAgent::CookieManager = 
```

I'll include the entire generated RBI in an expandable block at the end.

I've tracked  the problem down to this call to [resolve constant](https://github.com/Shopify/tapioca/blob/master/lib/tapioca/compilers/symbol_table/symbol_generator.rb#L795) where it seems that we're failing to find `HTTPClient::CookieManager`. Thus, I think the resulting RBI should look like this:

```
WebAgent::CookieManager = HTTPClient::CookieManager
```

<details>
  <summary>Full RBI</summary>

```
# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `httpclient` gem.
# Please instead update this file by running `tapioca sync`.

# typed: true

module HTTP
  extend(::HTTP::Chainable)

  class << self
    def [](headers); end
  end
end

HTTP::CHARSET_RE = T.let(T.unsafe(nil), Regexp)

class HTTP::ContentType < ::Struct
  def charset; end
  def charset=(_); end
  def mime_type; end
  def mime_type=(_); end

  class << self
    def [](*_arg0); end
    def inspect; end
    def members; end
    def new(*_arg0); end
    def parse(str); end

    private

    def charset(str); end
    def mime_type(str); end
  end
end

HTTP::MIME_TYPE_RE = T.let(T.unsafe(nil), Regexp)

class HTTP::Message
  def initialize; end

  def body; end
  def body=(body); end
  def body_encoding; end
  def code; end
  def content; end
  def content_type; end
  def content_type=(content_type); end
  def contenttype; end
  def contenttype=(content_type); end
  def cookies; end
  def dump(dev = T.unsafe(nil)); end
  def header; end
  def headers; end
  def http_body; end
  def http_body=(body); end
  def http_header; end
  def http_header=(_arg0); end
  def http_version; end
  def http_version=(http_version); end
  def ok?; end
  def peer_cert; end
  def peer_cert=(_arg0); end
  def previous; end
  def previous=(_arg0); end
  def reason; end
  def reason=(reason); end
  def redirect?; end
  def see_other?; end
  def status; end
  def status=(status); end
  def status_code; end
  def version; end
  def version=(version); end

  class << self
    def create_query_part_str(query); end
    def escape(str); end
    def escape_query(query); end
    def file?(obj); end
    def get_mime_type_func; end
    def internal_mime_type(path); end
    def keep_alive_enabled?(version); end
    def mime_type(path); end
    def mime_type_handler; end
    def mime_type_handler=(handler); end
    def multiparam_query?(query); end
    def new_connect_request(uri); end
    def new_request(method, uri, query = T.unsafe(nil), body = T.unsafe(nil), boundary = T.unsafe(nil)); end
    def new_response(body, req = T.unsafe(nil)); end
    def parse(query); end
    def set_mime_type_func(handler); end
    def unescape(string); end
  end
end

class HTTP::Message::Body
  def initialize; end

  def chunk_size; end
  def chunk_size=(_arg0); end
  def content; end
  def dump(header = T.unsafe(nil), dev = T.unsafe(nil)); end
  def dump_chunked(header = T.unsafe(nil), dev = T.unsafe(nil)); end
  def init_request(body = T.unsafe(nil), boundary = T.unsafe(nil)); end
  def init_response(body = T.unsafe(nil)); end
  def positions; end
  def positions=(_arg0); end
  def size; end

  private

  def build_query_multipart_str(query, boundary); end
  def dump_chunk(str); end
  def dump_chunk_size(size); end
  def dump_chunks(io, dev); end
  def dump_file(io, dev, sz); end
  def dump_last_chunk; end
  def params_from_file(value); end
  def remember_pos(io); end
  def reset_pos(io); end
  def set_content(body, boundary = T.unsafe(nil)); end
end

HTTP::Message::Body::DEFAULT_CHUNK_SIZE = T.let(T.unsafe(nil), Integer)

class HTTP::Message::Body::Parts
  def initialize; end

  def add(part); end
  def parts; end
  def size; end
  def sizes; end

  private

  def add_size(part, sz); end
end

HTTP::Message::CRLF = T.let(T.unsafe(nil), String)

class HTTP::Message::Headers
  def initialize; end

  def [](key); end
  def []=(key, value); end
  def add(key, value); end
  def all; end
  def body_charset; end
  def body_charset=(_arg0); end
  def body_date; end
  def body_date=(_arg0); end
  def body_encoding; end
  def body_size; end
  def body_size=(body_size); end
  def body_type; end
  def body_type=(_arg0); end
  def chunked; end
  def chunked=(_arg0); end
  def content_type; end
  def content_type=(content_type); end
  def contenttype; end
  def contenttype=(content_type); end
  def create_query_part; end
  def create_query_uri; end
  def delete(key); end
  def dump; end
  def get(key = T.unsafe(nil)); end
  def http_version; end
  def http_version=(_arg0); end
  def init_connect_request(uri); end
  def init_request(method, uri, query = T.unsafe(nil)); end
  def init_response(status_code, req = T.unsafe(nil)); end
  def reason_phrase; end
  def reason_phrase=(_arg0); end
  def request_absolute_uri; end
  def request_absolute_uri=(_arg0); end
  def request_method; end
  def request_query; end
  def request_query=(_arg0); end
  def request_uri; end
  def request_uri=(_arg0); end
  def set(key, value); end
  def set_body_encoding; end
  def set_date_header; end
  def set_headers(headers); end
  def status_code; end
  def status_code=(status_code); end

  private

  def charset_label; end
  def request_line; end
  def response_status_line; end
  def set_header; end
  def set_request_header; end
  def set_response_header; end
end

HTTP::Message::Headers::CHARSET_MAP = T.let(T.unsafe(nil), Hash)

HTTP::Message::Headers::NIL_URI = T.let(T.unsafe(nil), T.untyped)

HTTP::Message::Headers::STATUS_CODE_MAP = T.let(T.unsafe(nil), Hash)

HTTP::Message::VERSION_WARNING = T.let(T.unsafe(nil), String)

module HTTP::Status
  class << self
    def redirect?(status); end
    def successful?(status); end
  end
end

HTTP::Status::ACCEPTED = T.let(T.unsafe(nil), Integer)

HTTP::Status::BAD_REQUEST = T.let(T.unsafe(nil), Integer)

HTTP::Status::CREATED = T.let(T.unsafe(nil), Integer)

HTTP::Status::FOUND = T.let(T.unsafe(nil), Integer)

HTTP::Status::INTERNAL = T.let(T.unsafe(nil), Integer)

HTTP::Status::MOVED_PERMANENTLY = T.let(T.unsafe(nil), Integer)

HTTP::Status::MOVED_TEMPORARILY = T.let(T.unsafe(nil), Integer)

HTTP::Status::NON_AUTHORITATIVE_INFORMATION = T.let(T.unsafe(nil), Integer)

HTTP::Status::NO_CONTENT = T.let(T.unsafe(nil), Integer)

HTTP::Status::OK = T.let(T.unsafe(nil), Integer)

HTTP::Status::PARTIAL_CONTENT = T.let(T.unsafe(nil), Integer)

HTTP::Status::PROXY_AUTHENTICATE_REQUIRED = T.let(T.unsafe(nil), Integer)

HTTP::Status::REDIRECT_STATUS = T.let(T.unsafe(nil), Array)

HTTP::Status::RESET_CONTENT = T.let(T.unsafe(nil), Integer)

HTTP::Status::SEE_OTHER = T.let(T.unsafe(nil), Integer)

HTTP::Status::SUCCESSFUL_STATUS = T.let(T.unsafe(nil), Array)

HTTP::Status::TEMPORARY_REDIRECT = T.let(T.unsafe(nil), Integer)

HTTP::Status::UNAUTHORIZED = T.let(T.unsafe(nil), Integer)

HTTP::VERSION = T.let(T.unsafe(nil), String)

HTTPClient = WebMockHTTPClient

JSONClient = WebMockJSONClient

class OpenSSL::X509::Store
  def initialize(*args); end

  def _httpclient_cert_store_items; end
  def add_cert(cert); end
  def add_file(cert); end
  def add_path(cert); end
end

class WebAgent
end

class WebAgent::Cookie < ::HTTP::Cookie
  def domain; end
  def flag; end
  def http_only?; end
  def original_domain; end
  def url; end
  def url=(url); end

  private

  def deprecated(old, new); end
end

WebAgent::CookieManager = 

```  

</details>

**Comment by RyanBrushett** [comment] 2021-01-11 18:18
Indeed, passing `inherit: true` to const_get in that particular call seems to fix the problem but I'm currently having a bit of trouble making a testcase for it.

**Comment by KaanOzkan** [comment] 2021-01-11 18:52
I'm curious if what's happening here is that tapioca is unable to load `httpclient/lib/httpclient/cookie.rb` fully and as a result we end up skipping the loading of `HTTPClient::CookieManager`. Interesting stuff is going on while loading this file
https://github.com/nahi/httpclient/blob/master/lib/httpclient/cookie.rb#L218.

Could it be due to some `LoadError`s from https://github.com/nahi/httpclient/blob/master/lib/httpclient/cookie.rb#L5-L6?

I'm just contemplating because I assume `inherit: true` is not a valid option for us. I'm curious if [manual gem requires](https://github.com/Shopify/tapioca#manual-gem-requires) fixes the issue 🤔 . Regardless a syntax error is definitely not what we want.

**Comment by RyanBrushett** [comment] 2021-01-11 19:10
I haven't been able to get it to render the right thing with any combination of manual requires that I've tried but I may well be missing something.
Yeah the loading behaviour is really interesting eh?

**Comment by RyanBrushett** [comment] 2021-01-11 19:32
@KaanOzkan I spoke too soon, you're onto something.
I added `require 'httpclient/webagent-cookie'` to the `require.rb` and it now passes a typecheck. The RBI still looks a little off, it has a line that is just `WebAgent::CookieManager = ` but this seems like progress 🎉

**Comment by KaanOzkan** [comment] 2021-01-11 19:49
That file doesn't seem to be loaded by the gem by default. So It does make sense that with the manual require we are able to now define `CookieManager` with https://github.com/nahi/httpclient/blob/master/lib/httpclient/webagent-cookie.rb#L458. I assume typecheck error was from `WebAgent::CookieManager`.

I don't know what's going on with that line. For a "working" example I took a look at the generated line
`JSONClient = WebMockJSONClient`. It seems to be due to https://github.com/bblimke/webmock/blob/7fe60a8696bb106abc0b21d9d9f27607357f61ff/lib/webmock/http_lib_adapters/httpclient_adapter.rb#L26.

I can't find anything similar within `httpclient` gem for `WebAgent::CookieManager` and I haven't looked into generation of those constant assignments before.

**Comment by paracycle** [comment] 2021-01-11 20:26
The crux of the problem is that `Object.const_get("HTTPClient::CookieManager", false)` raises a `NameError` but ``Object.const_get("HTTPClient::CookieManager", true)` works. And we use that to check is the constant resolved by the name we found for a constant is indeed the same object when lookup the name of a constant.

So, this might be due to require ordering, but I still think there is a bug to fix here. Basically Tapioca should never be generating nothing on the right-hand side of a constant alias.

**Comment by RyanBrushett** [comment] 2021-01-11 20:38
Digging through the RBI files for my project, it appears that this isn't the only place this comes up. It seems like the only reason I caught this particular one was because it was at the end of the file so the trailing empty assignment caused an error. Hmm

**Closed** 2021-01-12 20:50 UTC
Labels: bug
