### ISSUE TITLE
tapioca dsl crashes inside tmux

### ISSUE THREAD

**Issue by olivierbuffon** [Shopify/tapioca#1555] opened 2023-07-05 16:47 UTC
Hey guys!
I recently exprienced a weird behaviour when trying to run the `tapioca dsl` command inside a Tmux session.
For some reasons it started to crash randomly (like 90% of the time) with an error ending like this:
```
/Users/olivierbuffon/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/parallel-1.23.0/lib/parallel.rb:83:in `rescue in work': Parallel::DeadWorker (Parallel::DeadWorker)
        from /Users/olivierbuffon/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/parallel-1.23.0/lib/parallel.rb:80:in `work'
        from /Users/olivierbuffon/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/parallel-1.23.0/lib/parallel.rb:522:in `block (4 levels) in work_in_processes'
        from /Users/olivierbuffon/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/parallel-1.23.0/lib/parallel.rb:637:in `with_instrumentation'
        from /Users/olivierbuffon/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/parallel-1.23.0/lib/parallel.rb:521:in `block (3 levels) in work_in_processes'
        from /Users/olivierbuffon/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/parallel-1.23.0/lib/parallel.rb:509:in `loop'
        from /Users/olivierbuffon/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/parallel-1.23.0/lib/parallel.rb:509:in `block (2 levels) in work_in_processes'
        from /Users/olivierbuffon/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/parallel-1.23.0/lib/parallel.rb:219:in `block (4 levels) in in_threads'
<internal:marshal>:34:in `load': end of file reached (EOFError)
        from /Users/olivierbuffon/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/parallel-1.23.0/lib/parallel.rb:81:in `work'
        from /Users/olivierbuffon/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/parallel-1.23.0/lib/parallel.rb:522:in `block (4 levels) in work_in_processes'
        from /Users/olivierbuffon/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/parallel-1.23.0/lib/parallel.rb:637:in `with_instrumentation'
        from /Users/olivierbuffon/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/parallel-1.23.0/lib/parallel.rb:521:in `block (3 levels) in work_in_processes'
        from /Users/olivierbuffon/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/parallel-1.23.0/lib/parallel.rb:509:in `loop'
        from /Users/olivierbuffon/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/parallel-1.23.0/lib/parallel.rb:509:in `block (2 levels) in work_in_processes'
        from /Users/olivierbuffon/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/parallel-1.23.0/lib/parallel.rb:219:in `block (4 levels) in in_threads'
```

Then I realized this same command on the same project outside tmux works like a charm.
For now it's not a blocker to me since I can still run it outside of tmux but it really anoying.

I'm running this on an Apple M1 Max and here are the versions I'm currently using in my project:
- `tapioca 0.11.7`
- `ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]`
- `rails 7.0.6`
- `tmux 3.3a`

I'm wondering if I'm the only one expriencing this issue 🤷🏻‍♂️ .

**Comment by KaanOzkan** [comment] 2023-07-06 18:25
We usually see this stack trace upon a OOM error although I never saw it on macos 🤔 . If you're running multiple tmux sessions the tmux server process might be using too much memory compared to running it outside tmux.

A workaround for the OOM would be to reduce the number of workers using `--workers` flag. For example, I'm hoping `workers=1` fixes it. You can experiment with higher worker counts as well.

**Comment by olivierbuffon** [comment] 2023-07-08 02:34
> A workaround for the OOM would be to reduce the number of workers using --workers flag. For example, I'm hoping workers=1 fixes it. You can experiment with higher worker counts as well.

Unfortunately this solution doesn't seem to work for this case. I'm still digging hope I'll be able to share some more info soon.

**Comment by KaanOzkan** [comment] 2023-07-10 20:39
Hmm 😕  let us know if you can extract it in a reproduction script. Not sure why it's crashing. Workers are attempting to talk to the parent process but it's killed.

**Comment by olivierbuffon** [comment] 2023-07-11 00:01
@KaanOzkan Hey! Just a quick message to inform you that I might have found the source of the problem. 
I'm not 100% sure for now, I still need to test it to confirm I can reproduce it with confidence. Here is what I found:
It appears that in my code I had a problem with a wrong active record association. For some reasons I forgot to remove one `has_many` in one of my models which caused an error saying the association didn't exists or something like that.
The error message I shared was actually triggered right after this step (with a huge error trace I couldn't even copy entirely), which partly explain why I didn't see this association error in the first place 😆.

Anyway, since I addressed this association error, the command `tapioca dsl` works like a charm in every evironment (tmux or not). It's been a couple of days I've been using it without any failure when before it was failing almost every time (at least in Tmux).

Like I said I'll try to reproduce it as soon as I have few minutes to confirm it's the source.
For now that's all I can share, hope it helps! Thanks @KaanOzkan ! :)

**Comment by alex-tan** [comment] 2023-07-12 15:51
+1 I also have this issue although have not found the cause. Using one worker fixes it.

Not using tmux.

- ruby 3.0.6p216
- tapioca (0.11.7)
- rails (7.0.6)

**Comment by olivierbuffon** [comment] 2023-07-12 16:46
@KaanOzkan Unfortunately I was finaly digging in the wrong direction again. The crash happened again.
BUT the good part is that I finally was able to extract the entire error trace I get when this is happening: [error_log.txt](https://github.com/Shopify/tapioca/files/12030320/error_log.txt).
I'll let you dig into it, but from what I saw it might be related to the `pg` gem?! If it's the case I found very strange this is happening more often inside Tmux 🤷🏻‍♂️ .
Anyway, for your information I'm running a Postgres Database on docker locally.
I'll continue digging this but let me know if you found something on your hand.

**Comment by KaanOzkan** [comment] 2023-07-12 17:22
@olivierbuffon We don't use postgres so we haven't ran into this issue before but looking at the repo quite a few users are reporting seg faults. I'm going to close this issue as I don't think this is a tapioca specific problem. 

Heplful thread: https://github.com/ged/ruby-pg/issues/311#issuecomment-1581764507, suggests using `export PGGSSENCMODE="disable"`. Hope that helps.

**Closed by KaanOzkan** 2023-07-12 17:22 UTC

**Comment by olivierbuffon** [comment] 2023-07-12 17:25
@KaanOzkan makes sense! No worries and thanks again for the help on this! Appreciated 🙏🏻

**Comment by robgraeber** [comment] 2025-02-03 23:12
Thanks @KaanOzkan you're the GOAT. Had a weird rosetta error + Parallel::DeadWorker and PGGSSENCMODE="disable" fixed it.
