### ISSUE TITLE
`ActiveRecordAssociations#type_for` incorrectly filters relations on classes with nested namespaces

### ISSUE THREAD

**Issue by jflinter** [Shopify/tapioca#603] opened 2021-11-08 23:46 UTC
Hello! I believe #584 introduced a regression that is causing some relations to be filtered out of generated RBI. [`ActiveRecord::Reflection#class_name`](https://github.com/rails/rails/blob/b0d14930458e9de0b68061b2bc341f87a973c2ba/activerecord/lib/active_record/reflection.rb#L166) returns a class that doesn't include a full namespace prefix, which in turn causes [`safe_constantize`](https://github.com/Shopify/tapioca/pull/584/files#diff-8d6f9eab330d7ad3102c9c4c7a8f58099275a00a48880b883d41fc0079ed36dbR275) to fail for classes that are inside a namespace, like this:

```rb
module Blog
  class Post < ActiveRecord::Base
    belongs_to :author
  end

  class Author < ActiveRecord::Base
  end
end
```

In the above example, when inspecting the :author relation, `class_name` will return `Author` (not `Blog::Author`) and `safe_constantize` won't be able to find that constant. As a result, no `author` method will show up in the generated RBI for `Post`. I should caveat that my application isn't using rails (just ActiveRecord) and so it's possible that this would work in a different environment. But regardless, I think the fix is to use `klass.name` instead of `class_name` in `ActiveRecordAssociations#type_for`:

```rb
class_name = if reflection.through_reflection?
  reflection.send(:delegate_reflection).klass.name
else
  reflection.klass.name
end
```

Thanks for your help!

**Comment by paracycle** [comment] 2021-11-26 19:13
Hey @jflinter, thanks for testing the latest changes and thanks for the very clear reproduction. Indeed the changes on `main` were falling short of namespaces, and that seems to be due to me misreading the behaviour of Active Record.

However, using `reflection.klass` is not the fix, since, if the reflection target class does not exist, then `reflection.klass` is the thing that throws an exception in the first place. The whole code change was to prevent that exception by detecting that situation earlier.

I have a fix for this that seems to work with your test case. I will be doing a couple of more checks on it and create a PR.

**Closed** 2021-11-29 15:08 UTC
