### ISSUE TITLE
`bundle exec tapioca init` giving a RuntimeError?

### ISSUE THREAD

**Issue by rabdelazim** [Shopify/tapioca#1683] opened 2023-10-09 18:51 UTC
I've already posted this to [stackOverflow](https://stackoverflow.com/questions/77261057/why-is-bundle-exec-tapioca-init-giving-a-runtimeerror) but hoping cross posting here will get more traction. Basically, `bundle exec tapioca init` gives the following stack trace:

```
Traceback (most recent call last):
    74: from /Users/ramy/.rvm/gems/ruby-2.7.5/bin/ruby_executable_hooks:22:in `<main>'
    73: from /Users/ramy/.rvm/gems/ruby-2.7.5/bin/ruby_executable_hooks:22:in `eval'
    72: from /Users/ramy/.rvm/gems/ruby-2.7.5/bin/tapioca:25:in `<main>'
    71: from /Users/ramy/.rvm/gems/ruby-2.7.5/bin/tapioca:25:in `load'
    70: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/exe/tapioca:25:in `<top (required)>'
    69: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
    68: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
    67: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
    66: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
    65: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/cli.rb:29:in `init'
    64: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.11064/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
    63: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.11064/lib/types/private/methods/_methods.rb:277:in `bind_call'
    62: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/runtime/trackers.rb:26:in `with_trackers_enabled'
    61: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/cli.rb:32:in `block in init'
    60: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/thor-1.2.2/lib/thor/invocation.rb:116:in `invoke'
    59: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
    58: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
    57: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
    56: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/cli.rb:239:in `gem'
    55: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca.rb:22:in `silence_warnings'
    54: from /Users/ramy/.rvm/rubies/ruby-2.7.5/lib/ruby/site_ruby/2.7.0/rubygems/user_interaction.rb:47:in `use_ui'
    53: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca.rb:23:in `block in silence_warnings'
    52: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/cli.rb:270:in `block in gem'
    51: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.11064/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
    50: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.11064/lib/types/private/methods/_methods.rb:277:in `bind_call'
    49: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/commands/gem.rb:115:in `sync'
    48: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.11064/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
    47: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.11064/lib/types/private/methods/_methods.rb:277:in `bind_call'
    46: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/commands/gem.rb:239:in `perform_additions'
    45: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/thor-1.2.2/lib/thor/shell/basic.rb:44:in `indent'
    44: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/commands/gem.rb:250:in `block in perform_additions'
    43: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.11064/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
    42: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.11064/lib/types/private/methods/_methods.rb:277:in `bind_call'
    41: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/executor.rb:31:in `run_in_parallel'
    40: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/parallel-1.22.1/lib/parallel.rb:294:in `map'
    39: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/parallel-1.22.1/lib/parallel.rb:457:in `work_in_processes'
    38: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/parallel-1.22.1/lib/parallel.rb:518:in `create_workers'
    37: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/parallel-1.22.1/lib/parallel.rb:518:in `each_with_index'
    36: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/parallel-1.22.1/lib/parallel.rb:518:in `each'
    35: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/parallel-1.22.1/lib/parallel.rb:519:in `block in create_workers'
    34: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/parallel-1.22.1/lib/parallel.rb:528:in `worker'
    33: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/parallel-1.22.1/lib/parallel.rb:528:in `fork'
    32: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/parallel-1.22.1/lib/parallel.rb:537:in `block in worker'
    31: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/parallel-1.22.1/lib/parallel.rb:557:in `process_incoming_jobs'
    30: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/parallel-1.22.1/lib/parallel.rb:587:in `call_with_index'
    29: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/commands/gem.rb:259:in `block (2 levels) in perform_additions'
    28: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.11064/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
    27: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.11064/lib/types/private/methods/_methods.rb:277:in `bind_call'
    26: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/commands/gem.rb:165:in `compile_gem_rbi'
    25: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.11064/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
    24: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.11064/lib/types/private/methods/_methods.rb:277:in `bind_call'
    23: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/gem/pipeline.rb:49:in `compile'
    22: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/gem/pipeline.rb:165:in `dispatch'
    21: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.11064/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
    20: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.11064/lib/types/private/methods/_methods.rb:277:in `bind_call'
    19: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/gem/pipeline.rb:200:in `on_node'
    18: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/gem/pipeline.rb:200:in `each'
    17: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/gem/pipeline.rb:200:in `block in on_node'
    16: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/gem/listeners/base.rb:26:in `dispatch'
    15: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.11064/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
    14: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.11064/lib/types/private/methods/_methods.rb:277:in `bind_call'
    13: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/gem/listeners/methods.rb:22:in `on_scope'
    12: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.11064/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
    11: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.11064/lib/types/private/methods/_methods.rb:277:in `bind_call'
    10: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/gem/listeners/methods.rb:37:in `compile_directly_owned_methods'
     9: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/gem/listeners/methods.rb:37:in `each'
     8: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/gem/listeners/methods.rb:38:in `block in compile_directly_owned_methods'
     7: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/gem/listeners/methods.rb:38:in `map'
     6: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/gem/listeners/methods.rb:49:in `block (2 levels) in compile_directly_owned_methods'
     5: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/gem/listeners/methods.rb:118:in `compile_method'
     4: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/gem/listeners/methods.rb:118:in `each'
     3: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/tapioca-0.11.2/lib/tapioca/gem/listeners/methods.rb:121:in `block in compile_method'
     2: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.11064/lib/types/private/abstract/declare.rb:38:in `block in declare_abstract'
     1: from /Users/ramy/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.11064/lib/types/private/abstract/declare.rb:38:in `tap'
/Users/ramy/.rvm/gems/ruby-2.7.5/gems/sorbet-runtime-0.5.11064/lib/types/private/abstract/declare.rb:40:in `block (2 levels) in declare_abstract': RBI::Param is declared as abstract; it cannot be instantiated (RuntimeError)

```

**Comment by KaanOzkan** [comment] 2023-10-10 19:09
Duplicate of https://github.com/Shopify/tapioca/issues/1592#issuecomment-1667944818. Updating to latest tapioca should fix it I believe.

**Closed by KaanOzkan** 2023-10-10 19:09 UTC
