### ISSUE TITLE
`Tapioca::Dsl::Compiler is already declared as abstract` on tapioca init

### ISSUE THREAD

**Issue by aaronabraham311** [Shopify/tapioca#1713] opened 2023-11-09 10:42 UTC
I am running on JRuby 9.4.4. I ran `bundle install` to install Sorbet and Tapioca. My Gemfile looks like this:

```
source 'https://rubygems.org'
gemspec

logstash_path = ENV['LOGSTASH_PATH'] || '/Users/aaronabraham/code/aaronabraham311/logstash-8.11.0'

if Dir.exist?(logstash_path)
  gem 'logstash-core', :path => "#{logstash_path}/logstash-core"
  gem 'logstash-core-plugin-api', :path => "#{logstash_path}/logstash-core-plugin-api"
end

# -- Dependencies --
gem 'sorbet', :group => :development
gem 'sorbet-runtime'
gem 'tapioca', require: false, :group => :development
```

When I run `bundle exec tapioca init`, I get the following error:
```
/Users/aaronabraham/.rvm/gems/jruby-9.4.4.0/gems/tapioca-0.11.12/lib/tapioca/runtime/trackers/constant_definition.rb:44: warning: tracing (e.g. set_trace_func) will not capture all events without --debug flag
RuntimeError: Tapioca::Dsl::Compiler is already declared as abstract
  declare_abstract at /Users/aaronabraham/.rvm/gems/jruby-9.4.4.0/gems/sorbet-runtime-0.5.11120/lib/types/private/abstract/declare.rb:10
         abstract! at /Users/aaronabraham/.rvm/gems/jruby-9.4.4.0/gems/sorbet-runtime-0.5.11120/lib/types/helpers.rb:21
  <class:Compiler> at /Users/aaronabraham/.rvm/gems/jruby-9.4.4.0/gems/tapioca-0.11.12/lib/tapioca/dsl/compiler.rb:17
      <module:Dsl> at /Users/aaronabraham/.rvm/gems/jruby-9.4.4.0/gems/tapioca-0.11.12/lib/tapioca/dsl/compiler.rb:6
  <module:Tapioca> at /Users/aaronabraham/.rvm/gems/jruby-9.4.4.0/gems/tapioca-0.11.12/lib/tapioca/dsl/compiler.rb:5
            <main> at /Users/aaronabraham/.rvm/gems/jruby-9.4.4.0/gems/tapioca-0.11.12/lib/tapioca/dsl/compiler.rb:4
           require at org/jruby/RubyKernel.java:1071
            <main> at /Users/aaronabraham/.rvm/gems/jruby-9.4.4.0/gems/tapioca-0.11.12/lib/tapioca/dsl.rb:15
           require at org/jruby/RubyKernel.java:1071
            <main> at /Users/aaronabraham/.rvm/gems/jruby-9.4.4.0/gems/tapioca-0.11.12/lib/tapioca/internal.rb:60
           require at org/jruby/RubyKernel.java:1071
  require_relative at org/jruby/RubyKernel.java:1100
            <main> at /Users/aaronabraham/.rvm/gems/jruby-9.4.4.0/gems/tapioca-0.11.12/exe/tapioca:23
              load at org/jruby/RubyKernel.java:1107
            <main> at /Users/aaronabraham/.rvm/gems/jruby-9.4.4.0/bin/tapioca:25
              eval at org/jruby/RubyKernel.java:1161
            <main> at /Users/aaronabraham/.rvm/gems/jruby-9.4.4.0/bin/jruby_executable_hooks:22
```

Any help would be appreciated!

**Comment by KaanOzkan** [comment] 2023-11-09 16:26
Duplicate of https://github.com/Shopify/tapioca/issues/1603

Unfortunately we don't use JRuby internally and haven't ran into this issue. It might be better to open an issue on JRuby code base and share the learnings in the issue linked above. From the stack trace it looks like we're loading the class twice, which executes https://github.com/sorbet/sorbet/blob/master/gems/sorbet-runtime/lib/types/private/abstract/declare.rb#L8-L10 a second time. I'm also not sure how reliable to JRuby support is inside sorbet https://github.com/sorbet/sorbet/issues/1216

**Closed by KaanOzkan** 2023-11-09 16:26 UTC
