### ISSUE TITLE
activesupport rbi does not include Benchmark.ms

### ISSUE THREAD

**Issue by BrianHicks** [Shopify/tapioca#1041] opened 2022-07-07 19:51 UTC
Running `tapioca gems` does not find `Benchmark.ms` defined in https://github.com/rails/rails/blob/v6.1.6/activesupport/lib/active_support/core_ext/benchmark.rb, even after adding `require active-support/core_ext/benchmark.rb`. Could be because it's defined like `class << Benchmark`?

I tried this on 0.8.2, 0.8.3, and 0.9.0. None of them successfully generate the method.

**Comment by Morriar** [comment] 2022-07-19 20:08
I looked at Sorbet and this is going to be very hard to fix.

Let's say we have this:

```rb
class << Foo
  def foo; end
end
```

My idea was to rewrite it as something like:

```rb
class Foo
  class << self
    def foo; end
  end
end
```

The problem is that at the `rewrite` phase, we do not know if `Foo` is a class or module so this code could be false.

Since the problem is not with Tapioca directly and it can be worked around with a shim, I'll close close this issue.

Sorry about that.

**Closed by Morriar** 2022-07-19 20:08 UTC
Labels: bug
