### ISSUE TITLE
undefined method `identifier' for #<Gem::Dependency:0x00007fc960079208> (NoMethodError)

### ISSUE THREAD

**Issue by aeldaly-tc** [Shopify/tapioca#229] opened 2021-02-15 15:13 UTC
I'm trying to run tapioca on my project and getting:

```
✔  bundle exec tapioca sync                                                                                                 99% (5:39) 🔋  3.00 L  RSpec: 60.00%
Removing RBI files of gems that have been removed:

bundler: failed to load command: tapioca (/Users/aeldaly/.rbenv/versions/2.7.2/bin/tapioca)
Traceback (most recent call last):
        54: from /Users/aeldaly/.rbenv/versions/2.7.2/bin/bundle:23:in `<main>'
        53: from /Users/aeldaly/.rbenv/versions/2.7.2/bin/bundle:23:in `load'
        52: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.9/exe/bundle:37:in `<top (required)>'
        51: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.9/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
        50: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.9/exe/bundle:49:in `block in <top (required)>'
        49: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.9/lib/bundler/cli.rb:24:in `start'
        48: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.9/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        47: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.9/lib/bundler/cli.rb:30:in `dispatch'
        46: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.9/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        45: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.9/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        44: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.9/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        43: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.9/lib/bundler/cli.rb:494:in `exec'
        42: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.9/lib/bundler/cli/exec.rb:28:in `run'
        41: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.9/lib/bundler/cli/exec.rb:63:in `kernel_load'
        40: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.9/lib/bundler/cli/exec.rb:63:in `load'
        39: from /Users/aeldaly/.rbenv/versions/2.7.2/bin/tapioca:23:in `<top (required)>'
        38: from /Users/aeldaly/.rbenv/versions/2.7.2/bin/tapioca:23:in `load'
        37: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/tapioca-0.4.14/exe/tapioca:6:in `<top (required)>'
        36: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
        35: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
        34: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
        33: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
        32: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/tapioca-0.4.14/lib/tapioca/cli.rb:92:in `sync'
        31: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/tapioca-0.4.14/lib/tapioca.rb:10:in `silence_warnings'
        30: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/user_interaction.rb:47:in `use_ui'
        29: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/tapioca-0.4.14/lib/tapioca.rb:11:in `block in silence_warnings'
        28: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/tapioca-0.4.14/lib/tapioca/cli.rb:93:in `block in sync'
        27: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.6289/lib/types/private/methods/_methods.rb:224:in `block in _on_method_added'
        26: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.6289/lib/types/private/methods/_methods.rb:224:in `call'
        25: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/tapioca-0.4.14/lib/tapioca/generator.rb:149:in `sync_rbis_with_gemfile'
        24: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.6289/lib/types/private/methods/_methods.rb:224:in `block in _on_method_added'
        23: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.6289/lib/types/private/methods/_methods.rb:224:in `call'
        22: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/tapioca-0.4.14/lib/tapioca/generator.rb:336:in `perform_removals'
        21: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.6289/lib/types/private/methods/_methods.rb:224:in `block in _on_method_added'
        20: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.6289/lib/types/private/methods/_methods.rb:224:in `call'
        19: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/tapioca-0.4.14/lib/tapioca/generator.rb:302:in `removed_rbis'
        18: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.6289/lib/types/private/methods/_methods.rb:224:in `block in _on_method_added'
        17: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.6289/lib/types/private/methods/_methods.rb:224:in `call'
        16: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/tapioca-0.4.14/lib/tapioca/generator.rb:274:in `expected_rbis'
        15: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.6289/lib/types/private/methods/_methods.rb:224:in `block in _on_method_added'
        14: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.6289/lib/types/private/methods/_methods.rb:224:in `call'
        13: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/tapioca-0.4.14/lib/tapioca/generator.rb:172:in `bundle'
        12: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/tapioca-0.4.14/lib/tapioca/generator.rb:172:in `new'
        11: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.6289/lib/types/private/methods/_methods.rb:224:in `block in _on_method_added'
        10: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.6289/lib/types/private/methods/_methods.rb:224:in `call'
         9: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/tapioca-0.4.14/lib/tapioca/gemfile.rb:34:in `initialize'
         8: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.6289/lib/types/private/methods/_methods.rb:224:in `block in _on_method_added'
         7: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.6289/lib/types/private/methods/_methods.rb:224:in `call'
         6: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/tapioca-0.4.14/lib/tapioca/gemfile.rb:62:in `load_dependencies'
         5: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.9/lib/bundler/spec_set.rb:80:in `materialize'
         4: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.9/lib/bundler/spec_set.rb:20:in `for'
         3: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.9/lib/bundler/spec_set.rb:20:in `loop'
         2: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.9/lib/bundler/spec_set.rb:22:in `block in for'
         1: from /Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.9/lib/bundler/spec_set.rb:22:in `include?'
/Users/aeldaly/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.9/lib/bundler/lazy_specification.rb:30:in `==': undefined method `identifier' for #<Gem::Dependency:0x00007fc960079208> (NoMethodError)
Did you mean?  identity
zsh: exit 1     bundle exec tapioca sync
```

Here is my gemfile
```
# frozen_string_literal: true

source 'https://rubygems.org'

gem 'karafka'
gem 'pg'
gem 'sequel'

gem 'sorbet-runtime'

group :development do
  gem 'rubocop'
  gem 'rubocop-rake'
  gem 'rubocop-rspec'
  gem 'rubocop-sequel'
  gem 'solargraph'
  gem 'sorbet'
  gem 'sorbet-progress'
  gem 'tapioca', require: false
end

group :development, :test do
  gem 'rspec'
end

group :test do
  gem 'database_cleaner-sequel'
  gem 'karafka-testing'
end
```

I also tried it by commenting out `sorbet-runtime`, `sorbet`, and `sorbet-progress` and running bundle install again.

I also tried following the instructions in https://github.com/Shopify/tapioca/issues/114

But they all fail with the same error.

Not sure how to proceed from here.

Thanks.

**Comment by KaanOzkan** [comment] 2021-02-16 18:58
Hello 👋 

I copy pasted your `Gemfile` into a test repo and ran `bundle install` followed by `bundle exec tapioca sync`. Looks like this is a regression on `bundler` as it's only occurring on `bundler` versions `2.2.8` and above. I did a quick look but nothing caught my eye so I suggest opening an issue within `bundler` at https://github.com/rubygems/rubygems/tree/master/bundler

In the meantime feel free to downgrade to `bundler 2.2.7` using `gem install bundler -v 2.2.7`. That should fix your issue.

**Comment by bmulholland** [comment] 2021-02-19 12:12
I'm running into this, too. There's no suitable bug listed over at bundler, though, and I'm afraid that I don't have enough information to file a bug myself. I'm pretty sure that anything I write up will be closed as actually a bug in tapioca. What should I even say the bug in bundler is?

**Comment by bmulholland** [comment] 2021-02-19 12:15
Also the suggested workaround doesn't work for me because the version of bundler I'm using (2.2.11) is a "default gem" that cannot be uninstalled.

**Comment by KaanOzkan** [comment] 2021-02-19 15:44
> Also the suggested workaround doesn't work for me because the version of bundler I'm using (2.2.11) is a "default gem" that cannot be uninstalled. (ruby 2.7.2)

If you do want to remove v2.2.11 as the default and instead make 2.2.7 the default you can remove the `.gemspec` file for bundler: `bundler-2.2.11.gemspec`. This file can be found under the `specifications/` folder where your gems are installed. You can find gem installation path with `gem env gempath`. Afterwards you can run `gem install bundler -v 2.2.7 --default`. There are more resources online https://dev.to/st0012/completely-remove-the-default-bundler-from-ci-environment-j0c.

If you don't want to remove default version of bundler but circumvent the issue you can use a specific version of bundler with `bundle _2.2.7_`. So the `tapioca sync` command would be `bundle _2.2.7_ exec tapioca sync`.

> I'm running into this, too. There's no suitable bug listed over at bundler, though, and I'm afraid that I don't have enough information to file a bug myself. I'm pretty sure that anything I write up will be closed as actually a bug in tapioca. What should I even say the bug in bundler is?

I'd need to take a closer look but even if it was closed I think bundler maintainers would give useful information to fix this issue in tapioca  thanks to their context 🙂 . Issue report can be simple and include the error stack trace as well as how it started occurring on `bundler 2.2.8`.

**Comment by paracycle** [comment] 2021-02-19 18:49
I submitted the issue here: https://github.com/rubygems/rubygems/issues/4394

**Comment by paracycle** [comment] 2021-02-24 23:57
Reopening this issue since this was **both** a Bundler regression **and** something Tapioca was not doing quite correctly. For more details, refer to the issue on the RubyGems repo, I've linked to above.

**Closed** 2021-02-25 18:01 UTC
Labels: bug

**Comment by paracycle** [comment] 2021-02-25 21:04
Thanks for the original problem report and pushing us on this issue, it made Tapioca better. ❤️ 
v0.4.15 released to Rubygems should work with new versions of Bundler now.
