### ISSUE TITLE
please add a CHANGELOG.md file

### ISSUE THREAD

**Issue by tilo** [Shopify/tapioca#1790] opened 2024-02-07 16:27 UTC
without a CHANGELOG file it is difficult to understand what changes were made, and if some are breaking changes

**Comment by Morriar** [comment] 2024-02-07 16:32
Dupe of https://github.com/Shopify/tapioca/issues/1768.

As answered to your other issue, _if_ we were to maintain a changelog file it would not contain anything different than the release description already does.

**Closed by Morriar** 2024-02-07 16:32 UTC
